spring:
  profiles: alpha
server:
  port: 8011
eureka:
  instance:
    hostname: eureka-alpha
  client:
    serviceUrl:
      defaultZone: http://eureka-bravo:8012/eureka/,http://eureka-charlie:8013/eureka/

---
spring:
  profiles: bravo
server:
  port: 8012
eureka:
  instance:
    hostname: eureka-bravo
  client:
    serviceUrl:
      defaultZone: http://eureka-alpha:8011/eureka/,http://eureka-charlie:8013/eureka/

---
spring:
  profiles: charlie
server:
  port: 8013
eureka:
  instance:
    hostname: eureka-charlie
  client:
    serviceUrl:
      defaultZone: http://eureka-alpha:8011/eureka/,http://eureka-bravo:8012/eureka/
